-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 21:58:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`client` (
  `idclient` INT NOT NULL,
  `nomclient` VARCHAR(45) NOT NULL,
  `clientcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`produit` (
  `idprod` INT NOT NULL,
  `nomprod` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idprod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`agent` (
  `idagent` INT NOT NULL,
  `nomagent` VARCHAR(45) NOT NULL,
  `prenomagent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idagent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`commande` (
  `numcommande` INT NOT NULL,
  `date` DATE NOT NULL,
  `prix` FLOAT NOT NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`numcommande`),
  INDEX `fk_commande_client1_idx` (`client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `blog`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `blog`.`ajouter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`ajouter` (
  `produit_idprod` INT NOT NULL,
  `agent_idagent` INT NOT NULL,
  PRIMARY KEY (`produit_idprod`, `agent_idagent`),
  INDEX `fk_produit_has_agent_agent1_idx` (`agent_idagent` ASC) VISIBLE,
  INDEX `fk_produit_has_agent_produit1_idx` (`produit_idprod` ASC) VISIBLE,
  CONSTRAINT `fk_produit_has_agent_produit1`
    FOREIGN KEY (`produit_idprod`)
    REFERENCES `blog`.`produit` (`idprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_has_agent_agent1`
    FOREIGN KEY (`agent_idagent`)
    REFERENCES `blog`.`agent` (`idagent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`contient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`contient` (
  `commande_numcommande` INT NOT NULL,
  `produit_idprod` INT NOT NULL,
  `quantité` INT NOT NULL,
  PRIMARY KEY (`commande_numcommande`, `produit_idprod`),
  INDEX `fk_commande_has_produit_produit1_idx` (`produit_idprod` ASC) VISIBLE,
  INDEX `fk_commande_has_produit_commande1_idx` (`commande_numcommande` ASC) VISIBLE,
  CONSTRAINT `fk_commande_has_produit_commande1`
    FOREIGN KEY (`commande_numcommande`)
    REFERENCES `blog`.`commande` (`numcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_has_produit_produit1`
    FOREIGN KEY (`produit_idprod`)
    REFERENCES `blog`.`produit` (`idprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
